# Generated by Django 3.2.19 on 2023-05-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='artist',
            field=models.CharField(max_length=200),
        ),
    ]
